In [23]:
import pandas as pd

septuagint_df = pd.read_parquet("hf://datasets/epaolinos/septuagint/data/train-00000-of-00001-1ac4cc64c0bad5a7.parquet")

In [24]:
septuagint_df['Book'].unique()

array(['ΓΕΝΕΣΙΣ', 'ΕΞΟΔΟΣ', 'ΛΕΥΙΤΙΚΟΝ', 'ΑΡΙΘΜΟΙ', 'ΔΕΥΤΕΡΟΝΟΜΙΟΝ',
       'ΙΗΣΟΥΣ', 'ΚΡΙΤΑΙ (Codex Alexandrinus)',
       'ΚΡΙΤΑΙ (Codex Vaticanus)', 'ΡΟΥΘ', 'ΒΑΣΙΛΕΙΩΝ Α (M 1Sam)',
       'ΒΑΣΙΛΕΙΩΝ Β (M 2Sam)', 'ΒΑΣΙΛΕΙΩΝ Γ (M 1Regn)',
       'ΒΑΣΙΛΕΙΩΝ Δ (M 2Regn)', 'ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Α', 'ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Β',
       'ΕΣΔΡΑΣ Α (liber apocryphus)', 'ΕΣΔΡΑΣ Β (M Esdr, Neh)', 'ΕΣΘΗΡ',
       'ΙΟΥΔΙΘ', 'ΤΩΒΙΤ (Codices Alexandrinus et Vaticanus)',
       'ΤΩΒΙΤ (Codex Sinaiticus)', 'ΜΑΚΚΑΒΑΙΩΝ Α', 'ΜΑΚΚΑΒΑΙΩΝ Β',
       'ΜΑΚΚΑΒΑΙΩΝ Γ', 'ΜΑΚΚΑΒΑΙΩΝ Δ', 'ΨΑΛΜΟΙ', 'ΩΔΑΙ', 'ΠΑΡΟΙΜΙΑΙ',
       'ΕΚΚΛΗΣΙΑΣΤΗΣ', 'ΑΣΜΑ', 'ΙΩΒ', 'ΣΟΦΙΑ ΣΑΛΩΜΩΝΟΣ', 'ΣΟΦΙΑ ΣΕΙΡΑΧ',
       'ΨΑΛΜΟΙ ΣΟΛΟΜΩΝΤΟΣ', 'ΩΣΗΕ', 'ΑΜΩΣ', 'ΜΙΧΑΙΑΣ', 'ΙΩΗΛ', 'ΑΒΔΙΟΥ',
       'ΙΩΝΑΣ', 'ΝΑΟΥΜ', 'ΑΜΒΑΚΟΥΜ', 'ΣΟΦΟΝΙΑΣ', 'ΑΓΓΑΙΟΣ', 'ΖΑΧΑΡΙΑΣ',
       'ΜΑΛΑΧΙΑΣ', 'ΗΣΑΙΑΣ', 'ΙΕΡΕΜΙΑΣ', 'ΒΑΡΟΥΧ', 'ΘΡΗΝΟΙ',
       'ΕΠΙΣΤΟΛΗ ΙΕΡΕΜΙΟΥ', 'ΙΕΖΕΚΙΗΛ', 'ΣΟΥΣΑΝΝΑ',
       'ΣΟΥΣΑΝΝΑ (Θεοδοτίων)', 'ΔΑΝΙΗΛ (LXX)', 'ΔΑΝΙΗΛ (Θεοδοτίων)',
       'ΒΗΛ ΚΑΙ ΔΡΑΚΩΝ'], dtype=object)

In [25]:
lxx_to_modern = {
    'ΓΕΝΕΣΙΣ': 'Genesis',
    'ΕΞΟΔΟΣ': 'Exodus',
    'ΛΕΥΙΤΙΚΟΝ': 'Leviticus',
    'ΑΡΙΘΜΟΙ': 'Numbers',
    'ΔΕΥΤΕΡΟΝΟΜΙΟΝ': 'Deuteronomy',
    'ΙΗΣΟΥΣ': 'Joshua',
    'ΚΡΙΤΑΙ (Codex Alexandrinus)': 'Judges (Alexandrinus)',
    'ΚΡΙΤΑΙ (Codex Vaticanus)': 'Judges (Vaticanus)',
    'ΡΟΥΘ': 'Ruth',
    'ΒΑΣΙΛΕΙΩΝ Α (M 1Sam)': '1 Samuel',
    'ΒΑΣΙΛΕΙΩΝ Β (M 2Sam)': '2 Samuel',
    'ΒΑΣΙΛΕΙΩΝ Γ (M 1Regn)': '1 Kings',
    'ΒΑΣΙΛΕΙΩΝ Δ (M 2Regn)': '2 Kings',
    'ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Α': '1 Chronicles',
    'ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Β': '2 Chronicles',
    'ΕΣΔΡΑΣ Α (liber apocryphus)': '1 Esdras',
    'ΕΣΔΡΑΣ Β (M Esdr, Neh)': 'Ezra-Nehemiah',
    'ΕΣΘΗΡ': 'Esther',
    'ΙΟΥΔΙΘ': 'Judith',
    'ΤΩΒΙΤ (Codices Alexandrinus et Vaticanus)': 'Tobit (Alexandrinus/Vaticanus)',
    'ΤΩΒΙΤ (Codex Sinaiticus)': 'Tobit (Sinaiticus)',
    'ΜΑΚΚΑΒΑΙΩΝ Α': '1 Maccabees',
    'ΜΑΚΚΑΒΑΙΩΝ Β': '2 Maccabees',
    'ΜΑΚΚΑΒΑΙΩΝ Γ': '3 Maccabees',
    'ΜΑΚΚΑΒΑΙΩΝ Δ': '4 Maccabees',
    'ΨΑΛΜΟΙ': 'Psalms',
    'ΩΔΑΙ': 'Odes',
    'ΠΑΡΟΙΜΙΑΙ': 'Proverbs',
    'ΕΚΚΛΗΣΙΑΣΤΗΣ': 'Ecclesiastes',
    'ΑΣΜΑ': 'Song of Solomon',
    'ΙΩΒ': 'Job',
    'ΣΟΦΙΑ ΣΑΛΩΜΩΝΟΣ': 'Wisdom of Solomon',
    'ΣΟΦΙΑ ΣΕΙΡΑΧ': 'Sirach',
    'ΨΑΛΜΟΙ ΣΟΛΟΜΩΝΤΟΣ': 'Psalms of Solomon',
    'ΩΣΗΕ': 'Hosea',
    'ΑΜΩΣ': 'Amos',
    'ΜΙΧΑΙΑΣ': 'Micah',
    'ΙΩΗΛ': 'Joel',
    'ΑΒΔΙΟΥ': 'Obadiah',
    'ΙΩΝΑΣ': 'Jonah',
    'ΝΑΟΥΜ': 'Nahum',
    'ΑΜΒΑΚΟΥΜ': 'Habakkuk',
    'ΣΟΦΟΝΙΑΣ': 'Zephaniah',
    'ΑΓΓΑΙΟΣ': 'Haggai',
    'ΖΑΧΑΡΙΑΣ': 'Zechariah',
    'ΜΑΛΑΧΙΑΣ': 'Malachi',
    'ΗΣΑΙΑΣ': 'Isaiah',
    'ΙΕΡΕΜΙΑΣ': 'Jeremiah',
    'ΒΑΡΟΥΧ': 'Baruch',
    'ΘΡΗΝΟΙ': 'Lamentations',
    'ΕΠΙΣΤΟΛΗ ΙΕΡΕΜΙΟΥ': 'Letter of Jeremiah',
    'ΙΕΖΕΚΙΗΛ': 'Ezekiel',
    'ΣΟΥΣΑΝΝΑ': 'Susanna',
    'ΣΟΥΣΑΝΝΑ (Θεοδοτίων)': 'Susanna (Theodotion)',
    'ΔΑΝΙΗΛ (LXX)': 'Daniel (LXX)',
    'ΔΑΝΙΗΛ (Θεοδοτίων)': 'Daniel (Theodotion)',
    'ΒΗΛ ΚΑΙ ΔΡΑΚΩΝ': 'Bel and the Dragon'
}

In [26]:
septuagint_df['Normalized Book'] = septuagint_df['Book'].replace(lxx_to_modern)

In [27]:
septuagint_df.head()

,Book,Chapter,Verse Number,Verse Text,Genre,Normalized Book
0,ΓΕΝΕΣΙΣ,1,1,Ἐν ἀρχῇ ἐποίησεν ὁ θεὸς τὸν οὐρανὸν καὶ τὴν γῆν.,Narrative,Genesis
1,ΓΕΝΕΣΙΣ,1,2,"ἡ δὲ γῆ ἦν ἀόρατος καὶ ἀκατασκεύαστος, καὶ σκό...",Narrative,Genesis
2,ΓΕΝΕΣΙΣ,1,3,καὶ εἶπεν ὁ θεός Γενηθήτω φῶς. καὶ ἐγένετο φῶς.,Narrative,Genesis
3,ΓΕΝΕΣΙΣ,1,4,καὶ εἶδεν ὁ θεὸς τὸ φῶς ὅτι καλόν. καὶ διεχώρι...,Narrative,Genesis
4,ΓΕΝΕΣΙΣ,1,5,καὶ ἐκάλεσεν ὁ θεὸς τὸ φῶς ἡμέραν καὶ τὸ σκότο...,Narrative,Genesis

In [37]:
septuagint_df['verse_ref'] = septuagint_df.apply(lambda row: f"{row['Normalized Book']} {row['Chapter']}:{row['Verse Number']}", axis=1)
septuagint_df.rename(columns={'Verse Text': 'text'}, inplace=True)
septuagint_df.head()

,Book,Chapter,Verse Number,text,Genre,Normalized Book,Normalized Reference,verse_ref
0,ΓΕΝΕΣΙΣ,1,1,Ἐν ἀρχῇ ἐποίησεν ὁ θεὸς τὸν οὐρανὸν καὶ τὴν γῆν.,Narrative,Genesis,Genesis 1:1,Genesis 1:1
1,ΓΕΝΕΣΙΣ,1,2,"ἡ δὲ γῆ ἦν ἀόρατος καὶ ἀκατασκεύαστος, καὶ σκό...",Narrative,Genesis,Genesis 1:2,Genesis 1:2
2,ΓΕΝΕΣΙΣ,1,3,καὶ εἶπεν ὁ θεός Γενηθήτω φῶς. καὶ ἐγένετο φῶς.,Narrative,Genesis,Genesis 1:3,Genesis 1:3
3,ΓΕΝΕΣΙΣ,1,4,καὶ εἶδεν ὁ θεὸς τὸ φῶς ὅτι καλόν. καὶ διεχώρι...,Narrative,Genesis,Genesis 1:4,Genesis 1:4
4,ΓΕΝΕΣΙΣ,1,5,καὶ ἐκάλεσεν ὁ θεὸς τὸ φῶς ἡμέραν καὶ τὸ σκότο...,Narrative,Genesis,Genesis 1:5,Genesis 1:5

In [28]:
NT_df = pd.read_parquet("hf://datasets/hmcgovern/original-language-bibles-greek/data/train-00000-of-00001.parquet")

In [29]:
NT_df.head()

,reference,text,transliteration,translation,dStrongs,manuscript_source
0,Mat.1.1.01,Βίβλος,Biblos,[The] book,G0976=N-NSF,NKO
1,Mat.1.1.02,γενέσεως,geneseōs,of [the] genealogy,G1078=N-GSF,NKO
2,Mat.1.1.03,Ἰησοῦ,Iēsou,of Jesus,G2424G=N-GSM-P,NKO
3,Mat.1.1.04,Χριστοῦ,Christou,Christ,G5547=N-GSM-T,NKO
4,Mat.1.1.05,υἱοῦ,huiou,son,G5207=N-GSM,NKO

In [30]:
# Common aliases that appear in your pair tables
book_aliases = {
    "matthew": "mat",
    "mark": "mrk",
    "luke": "luk",
    "john": "jhn",
    "acts": "act",
    "romans": "rom",
    "1 corinthians": "1co",
    "2 corinthians": "2co",
    "galatians": "gal",
    "ephesians": "eph",
    "philippians": "php",
    "colossians": "col",
    "1 thessalonians": "1th",
    "2 thessalonians": "2th",
    "1 timothy": "1ti",
    "2 timothy": "2ti",
    "titus": "tit",
    "philemon": "phm",
    "hebrews": "heb",
    "james": "jas",
    "1 peter": "1pe",
    "2 peter": "2pe",
    "1 john": "1jn",
    "2 john": "2jn", 
    "3 john": "3jn",
    "jude": "jud",
    "revelation": "rev",
}
# Create a lookup for abbreviations to full names
reverse_book_aliases = {v: k for k, v in book_aliases.items()}

In [31]:
parts = NT_df["reference"].astype(str).str.extract(
    r"^(?P<book>[^.]+)\.(?P<chapter>\d+)\.(?P<verse>\d+)(?:[\[\{\(][^\]\}\)]+[\]\}\)])?\.(?P<word>\d+)$"
)


tmp = NT_df.join(parts)

# Keep only rows where reference parsed correctly
tmp = tmp.dropna(subset=["book", "chapter", "verse", "word"]).copy()

# Safe numeric conversion
tmp["chapter"] = pd.to_numeric(tmp["chapter"], errors="coerce")
tmp["verse"] = pd.to_numeric(tmp["verse"], errors="coerce")
tmp["word"] = pd.to_numeric(tmp["word"], errors="coerce")
tmp = tmp.dropna(subset=["chapter", "verse", "word"]).copy()

tmp["chapter"] = tmp["chapter"].astype(int)
tmp["verse"] = tmp["verse"].astype(int)
tmp["word"] = tmp["word"].astype(int)

tmp["verse_ref"] = (
    tmp["book"] + "." + tmp["chapter"].astype(str) + "." + tmp["verse"].astype(str)
)

verse_df = (
    tmp.sort_values(["book", "chapter", "verse", "word"])
       .groupby("verse_ref", as_index=False, sort=False)
       .agg(
           text=("text", lambda s: " ".join(s.astype(str)))
       )
)

# print(verse_df.head(10))

# Optional: inspect bad references that failed parsing
bad_refs = NT_df.loc[parts.isna().any(axis=1), "reference"]
print("Unparsed refs sample:", bad_refs.head(20).tolist())

Unparsed refs sample: ['._Word']

In [32]:
verse_df.head()

  verse_ref                                               text
0   1Co.1.1  Παῦλος κλητὸς ἀπόστολος Χριστοῦ Ἰησοῦ διὰ θελή...
1   1Co.1.2  τῇ ἐκκλησίᾳ τοῦ θεοῦ τῇ οὔσῃ ἐν Κορίνθῳ, ἡγι...
2   1Co.1.3  χάρις ὑμῖν καὶ εἰρήνη ἀπὸ θεοῦ πατρὸς ἡμῶν καὶ...
3   1Co.1.4  Εὐχαριστῶ τῷ θεῷ μου πάντοτε περὶ ὑμῶν ἐπὶ τῇ...
4   1Co.1.5  ὅτι ἐν παντὶ ἐπλουτίσθητε ἐν αὐτῷ ἐν παντὶ λόγ...

In [33]:
def get_normalized_reference(token: str) -> str:
    try:
        book, chapter, verse = token.split('.')
    except ValueError:
        raise ValueError(f"Invalid token format: {token}. Expected format 'book.chapter.verse'.")
    book = book.strip().lower()
    book = reverse_book_aliases[book]
    chapter = chapter.strip()
    verse = verse.strip()
    return f"{book} {chapter}:{verse}"

def get_normalized_reference_df(df: pd.DataFrame, column: str) -> pd.DataFrame:
    df[column] = df[column].apply(get_normalized_reference)
    return df

nt_final_df = get_normalized_reference_df(verse_df, "verse_ref")
nt_final_df.head()

           verse_ref                                               text
0  1 corinthians 1:1  Παῦλος κλητὸς ἀπόστολος Χριστοῦ Ἰησοῦ διὰ θελή...
1  1 corinthians 1:2  τῇ ἐκκλησίᾳ τοῦ θεοῦ τῇ οὔσῃ ἐν Κορίνθῳ, ἡγι...
2  1 corinthians 1:3  χάρις ὑμῖν καὶ εἰρήνη ἀπὸ θεοῦ πατρὸς ἡμῶν καὶ...
3  1 corinthians 1:4  Εὐχαριστῶ τῷ θεῷ μου πάντοτε περὶ ὑμῶν ἐπὶ τῇ...
4  1 corinthians 1:5  ὅτι ἐν παντὶ ἐπλουτίσθητε ἐν αὐτῷ ἐν παντὶ λόγ...

In [41]:
ot_nt_final_df = pd.concat([nt_final_df, septuagint_df[['verse_ref', 'text']]], ignore_index=True)
ot_nt_final_df.head()

           verse_ref                                               text
0  1 corinthians 1:1  Παῦλος κλητὸς ἀπόστολος Χριστοῦ Ἰησοῦ διὰ θελή...
1  1 corinthians 1:2  τῇ ἐκκλησίᾳ τοῦ θεοῦ τῇ οὔσῃ ἐν Κορίνθῳ, ἡγι...
2  1 corinthians 1:3  χάρις ὑμῖν καὶ εἰρήνη ἀπὸ θεοῦ πατρὸς ἡμῶν καὶ...
3  1 corinthians 1:4  Εὐχαριστῶ τῷ θεῷ μου πάντοτε περὶ ὑμῶν ἐπὶ τῇ...
4  1 corinthians 1:5  ὅτι ἐν παντὶ ἐπλουτίσθητε ἐν αὐτῷ ἐν παντὶ λόγ...

In [42]:
print(ot_nt_final_df.head())
print(f"length of ot_nt_final_df: {len(ot_nt_final_df)}")

           verse_ref                                               text
0  1 corinthians 1:1  Παῦλος κλητὸς ἀπόστολος Χριστοῦ Ἰησοῦ διὰ θελή...
1  1 corinthians 1:2  τῇ ἐκκλησίᾳ τοῦ θεοῦ τῇ οὔσῃ ἐν Κορίνθῳ, ἡγι...
2  1 corinthians 1:3  χάρις ὑμῖν καὶ εἰρήνη ἀπὸ θεοῦ πατρὸς ἡμῶν καὶ...
3  1 corinthians 1:4  Εὐχαριστῶ τῷ θεῷ μου πάντοτε περὶ ὑμῶν ἐπὶ τῇ...
4  1 corinthians 1:5  ὅτι ἐν παντὶ ἐπλουτίσθητε ἐν αὐτῷ ἐν παντὶ λόγ...
length of ot_nt_final_df: 38526

In [ ]:
# ot_nt_final_df.to_csv("bible_corpus.csv", index=False)